name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./service
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/install-action@nextest
      - name: Build
        run: cargo build --verbose  
      - name: Run tests
        run: cargo nextest run --verbose
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --codecov --output-path codecov.json
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
            files: codecov.json
            fail_ci_if_error: true
